services:
  - type: web
    name: form-estudiantes
    env: node
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: DATABASE_URL
        sync: false  # This will be set in the Render dashboard